server:
  port: 8202

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos-url}:8001
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: ${rabbitmq-url}
    port: 5672
    username: aires
    password: 5566
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  application:
    name: aires-cloud-server-system-test
  boot:
    admin:
      client:
        url: http://${aires-cloud-monitor-admin}:8401
        username: aires
        password: 5566

#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 20
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    instance-info-replication-interval-seconds: 30
#    serviceUrl:
#      defaultZone: http://aires:5566@${aires-cloud-register-eureka}:8001/register/eureka/
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://${aires-cloud-gateway-zuul}:8301/auth/user
feign:
  hystrix:
    enabled: true
# 把SecurityContext对象从你当前主线程传输到Hystrix线程
hystrix:
  shareSecurityContext: true
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS